apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
    - name: http-localhost-srv
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: http-localhost-src
      protocol: TCP
      port: 4001
      targetPort: 4001
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: languagekit-api
          image: hexpm/elixir:1.15.7-erlang-26.1.2-debian-bookworm-20231009
          imagePullPolicy: Never
          command: ["tail", "-f", "/src/README.md"]
          ports:
            - containerPort: 4000
            - containerPort: 4001
          volumeMounts:
            - name: ext4-api-code
              mountPath: /src
          resources:
            requests:
              memory: "2048Mi"
              cpu: "1024m"
            limits:
              memory: "2048Mi"
              cpu: "1024m"
      volumes:
        - name: ext4-api-code
          hostPath:
            path: <API_CODE_PATH>
