import Config

# Configure your database
config :languagekit, Languagekit.Repo,
  username: "languagekit",
  password: "languagekit",
  hostname: "postgres-0",
  database: "languagekit_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :users, Users.Repo,
  username: "languagekit",
  password: "languagekit",
  hostname: "postgres-0",
  database: "users_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :languages, Languages.Repo,
  username: "languagekit",
  password: "languagekit",
  hostname: "postgres-0",
  database: "languages_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :languagekit_web, LanguagekitWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "A0ub0e/zIcbucqaFF6BrGY6R0NdqZNdoZN9co4MYYGZKbE8TH4HTLkYjzu7wLgf2",
  watchers: []

config :users, Users.Guardian,
  issuer: "languagekit",
  secret_key: "dhXVeuozzrIOD/54X7IST884tY6pPCwwtLuGOoKSUBYXabgFEP8jsSlrE6wO069O"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :languagekit_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20
